import itertools
import math
import numpy as np

# CATHEDRAL CANONICAL HODGE AUDIT
# Reconstructs only the incidence/Hodge core.
# No observed constants and no physics-label attachment.

phi = (1.0 + math.sqrt(5.0)) / 2.0

# 12 icosahedral shell vertices
verts = []
for a, b in [(1.0, phi), (1.0, -phi), (-1.0, phi), (-1.0, -phi)]:
    verts.append((0.0, a, b))
    verts.append((a, b, 0.0))
    verts.append((b, 0.0, a))
verts = np.asarray(verts, dtype=float)

# Shell adjacency from the minimum nonzero distance
diff = verts[:, None, :] - verts[None, :, :]
dist = np.linalg.norm(diff, axis=-1)
mind = np.min(dist[dist > 1.0e-10])
A = np.isclose(dist, mind, atol=1.0e-10).astype(float)
np.fill_diagonal(A, 0.0)

shell_edges = [
    (i, j)
    for i in range(12)
    for j in range(i + 1, 12)
    if A[i, j] > 0.5
]

faces = [
    tri
    for tri in itertools.combinations(range(12), 3)
    if A[tri[0], tri[1]] > 0.5
    and A[tri[0], tri[2]] > 0.5
    and A[tri[1], tri[2]] > 0.5
]

# Orient shell faces outward
oriented_faces = []
for i, j, k in faces:
    p, q, r = verts[i], verts[j], verts[k]
    normal = np.cross(q - p, r - p)
    centroid = (p + q + r) / 3.0
    if np.dot(normal, centroid) < 0.0:
        j, k = k, j
    oriented_faces.append((i, j, k))

# Centred closure: 13 vertices, 30 shell edges + 12 spokes, 20 shell faces
center = 12
all_edges = shell_edges + [(i, center) for i in range(12)]
edge_index = {edge: idx for idx, edge in enumerate(all_edges)}

d0 = np.zeros((len(all_edges), 13), dtype=float)
for row, (i, j) in enumerate(all_edges):
    d0[row, i] = -1.0
    d0[row, j] = 1.0

d1 = np.zeros((len(oriented_faces), len(all_edges)), dtype=float)
for frow, (i, j, k) in enumerate(oriented_faces):
    for u, v in [(i, j), (j, k), (k, i)]:
        edge = (min(u, v), max(u, v))
        sign = 1.0 if (u, v) == edge else -1.0
        d1[frow, edge_index[edge]] = sign

chain_error = float(np.max(np.abs(d1 @ d0)))

L0 = d0.T @ d0
L1 = d0 @ d0.T + d1.T @ d1
L2 = d1 @ d1.T

D = np.block([
    [np.zeros((13, 13)), d0.T, np.zeros((13, 20))],
    [d0, np.zeros((42, 42)), d1.T],
    [np.zeros((20, 13)), d1, np.zeros((20, 20))],
])

def nullity(matrix: np.ndarray, tol: float = 1.0e-9) -> int:
    return int(matrix.shape[1] - np.linalg.matrix_rank(matrix, tol=tol))

b0 = nullity(L0)
b1 = nullity(L1)
b2 = nullity(L2)
euler_cells = 13 - 42 + 20
euler_betti = b0 - b1 + b2

# Unoriented face-vertex incidence shadow kernel
B = np.zeros((20, 12), dtype=float)
for row, tri in enumerate(faces):
    for v in tri:
        B[row, v] = 1.0

B_rank = int(np.linalg.matrix_rank(B, tol=1.0e-10))
shadow_dim = 20 - B_rank

# Face-dual graph and hidden curvature spectrum
A_face = np.zeros((20, 20), dtype=float)
for i in range(20):
    for j in range(i + 1, 20):
        if len(set(faces[i]).intersection(faces[j])) == 2:
            A_face[i, j] = 1.0
            A_face[j, i] = 1.0
L_face = np.diag(A_face.sum(axis=1)) - A_face

_, _, vh = np.linalg.svd(B.T, full_matrices=True)
Qh = vh.T[:, B_rank:]
hidden_eigs = np.linalg.eigvalsh(Qh.T @ L_face @ Qh)

def grouped(values: np.ndarray, decimals: int = 9):
    vals, counts = np.unique(np.round(values, decimals), return_counts=True)
    return list(zip(vals.tolist(), counts.tolist()))

print("=" * 72)
print("CATHEDRAL CANONICAL HODGE AUDIT")
print("=" * 72)
print(f"shell vertices          = {len(verts)}")
print(f"shell edges             = {len(shell_edges)}")
print(f"shell faces             = {len(faces)}")
print(f"centred C^0 dimension   = {d0.shape[1]}")
print(f"centred C^1 dimension   = {d0.shape[0]}")
print(f"centred C^2 dimension   = {d1.shape[0]}")
print(f"max |d1 d0|             = {chain_error:.3e}")
print()
print("BETTI / EULER")
print(f"b0, b1, b2              = {b0}, {b1}, {b2}")
print(f"Euler from cells        = {euler_cells}")
print(f"Euler from Betti        = {euler_betti}")
print(f"|Euler|                 = {abs(euler_cells)}")
print(f"dim ker(D)              = {nullity(D)}")
print()
print("CENTRED 0-FORM LAPLACIAN")
print(grouped(np.linalg.eigvalsh(L0)))
print()
print("FACE-INCIDENCE SHADOW")
print(f"rank(B)                 = {B_rank}")
print(f"dim ker(B^T)            = {shadow_dim}")
print("hidden face spectrum    =", grouped(hidden_eigs))
print()
print("EXACT CORE INDEX CHAIN")
print(f"|chi(X)|^2              = {abs(euler_cells) ** 2}")
print(f"1/|chi(X)|^2            = {1.0 / (abs(euler_cells) ** 2):.15f}")
print(f"b1                      = {b1}")
print(f"dim ker(D)              = {nullity(D)}")
print()
print("AUDIT RESULT")
print("The incidence/Hodge core deterministically emits 9, 11, 13 and an 8=4+4")
print("face-incidence shadow. Physics labels require an additional internal-algebra")
print("construction; they are not generated by the bare Hodge complex alone.")