#!/usr/bin/env python3
"""URT contraction selector and certified-locality continuation.

This target-blind certificate starts from the already proved sharp spectral
envelopes of the normalized A4 Wilson kernel

    H_r(p)^2 = ||S(p)||^2 + (r B(p)-1)^2.

It proves three things.

1. If the declared URT selection principle is made precise as maximizing the
   scale-free worst-mode contraction of the positive quadratic relaxation
   generated by H_r^2, then the selected coefficient is exactly the existing
   algebraic minimax root.  No new objective is introduced: optimal Richardson
   relaxation is a monotone function of the same exact spectral ratio.
2. Any uniform polynomial/polar iteration whose convergence factor is a
   strictly increasing function of the kernel condition number selects the
   same coefficient.  The complex-strip maximizer is therefore not a competing
   selector under this precise URT rule, although it remains a useful locality
   diagnostic.
3. A direct perturbation bound gives a certified nonzero complex strip at the
   selected coefficient.  This proves exponential locality exists without
   claiming that the previously searched nearest singularity is global.

The calculation uses no masses, mixing data, or other observational targets.
It does not select the determinant-line phase or the full microscopic action.
"""

from __future__ import annotations

import argparse
import json
import math
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Any

from scipy.optimize import brentq


ROOT_BRACKET = (1.16954339716037, 1.16954339716038)
R_LOCALITY_PROXY = 1.3114150071596995
TAU_CERTIFIED = 0.031


def stationarity_polynomial(r: float) -> float:
    return 240.0 * r**3 - 392.0 * r**2 - 28.0 * r + 185.0


def spectral_endpoints(r: float) -> tuple[float, float]:
    """Exact lower/upper H^2 endpoints on the minimax branch."""
    lower = (2.0 * r - 2.25) / (r * r - 1.25)
    upper = (2.5 * r - 1.0) ** 2
    return lower, upper


def relaxation_data(r: float) -> dict[str, float]:
    lower, upper = spectral_endpoints(r)
    condition_h_squared = upper / lower
    condition_h = math.sqrt(condition_h_squared)

    # Optimal Richardson iteration for the positive Hessian H^2:
    # x_{n+1}=(I-alpha H^2)x_n.
    richardson_step_h_squared = 2.0 / (lower + upper)
    richardson_factor_h_squared = (upper - lower) / (upper + lower)

    # The analogous scale-free factor for the positive magnitude |H|.  It is
    # also the standard monotone Chebyshev/CG factor for the H^2 interval.
    h_min = math.sqrt(lower)
    h_max = math.sqrt(upper)
    richardson_step_abs_h = 2.0 / (h_min + h_max)
    richardson_factor_abs_h = (h_max - h_min) / (h_max + h_min)

    # A commonly used asymptotic polynomial factor.  It is included only to
    # show that all monotone condition-number criteria have the same r.
    chebyshev_factor_h_squared = (
        math.sqrt(condition_h_squared) - 1.0
    ) / (math.sqrt(condition_h_squared) + 1.0)

    return {
        "r": r,
        "H_squared_minimum": lower,
        "H_squared_maximum": upper,
        "condition_number_H_squared": condition_h_squared,
        "condition_number_H": condition_h,
        "optimal_Richardson_step_for_H_squared": richardson_step_h_squared,
        "optimal_Richardson_factor_for_H_squared": richardson_factor_h_squared,
        "optimal_Richardson_step_for_abs_H": richardson_step_abs_h,
        "optimal_Richardson_factor_for_abs_H": richardson_factor_abs_h,
        "Chebyshev_factor_for_H_squared": chebyshev_factor_h_squared,
    }


def certified_strip_bound(r_lower: str, r_upper: str, tau: str) -> dict[str, Any]:
    """Conservative decimal/rational-style zero-exclusion certificate.

    For q=p+i eta with ||eta||<=tau, every A4 root alpha has
    |alpha.eta|<=sqrt(2) tau.  The elementary inequality

        sinh(x) <= x/(1-x),  0<=x<1,

    avoids relying on a floating transcendental interval implementation.  We
    deliberately replace sqrt(2), sqrt(5), and r by outward upper decimals.
    """
    getcontext().prec = 70
    rl = Decimal(r_lower)
    ru = Decimal(r_upper)
    t = Decimal(tau)

    # Strict outward rational bounds: sqrt(2)<1.415 and sqrt(5)<2.237.
    sqrt2_upper = Decimal("1.415")
    sqrt5_upper = Decimal("2.237")
    x_upper = sqrt2_upper * t
    sinh_upper = x_upper / (Decimal(1) - x_upper)

    delta_s_upper = Decimal(2) * sqrt2_upper * sinh_upper
    delta_b_upper = Decimal(2) * sinh_upper
    real_w_upper = Decimal("2.5") * ru - Decimal(1)

    perturbation_upper = (
        delta_s_upper * (sqrt5_upper + delta_s_upper)
        + ru
        * delta_b_upper
        * (Decimal(2) * real_w_upper + ru * delta_b_upper)
    )

    def lower_endpoint(value: Decimal) -> Decimal:
        return (
            Decimal(2) * value - Decimal("2.25")
        ) / (value * value - Decimal("1.25"))

    # The bracket is tiny; taking the smaller endpoint value is a conservative
    # bound without assuming a derivative sign inside the bracket.
    gap_lower = min(lower_endpoint(rl), lower_endpoint(ru))
    margin = gap_lower - perturbation_upper

    return {
        "strip_radius_proved": float(t),
        "root_norm_bound": "|alpha.eta| <= sqrt(2)||eta||",
        "elementary_transcendental_bound": "sinh(x)<=x/(1-x) for 0<=x<1",
        "outward_bounds": {
            "sqrt(2)_upper": str(sqrt2_upper),
            "sqrt(5)_upper": str(sqrt5_upper),
            "r_lower": str(rl),
            "r_upper": str(ru),
            "sinh(sqrt(2)tau)_upper": str(sinh_upper),
        },
        "H_squared_real_torus_gap_lower": str(gap_lower),
        "complex_perturbation_upper": str(perturbation_upper),
        "strict_positive_margin": str(margin),
        "zero_exclusion": bool(margin > 0),
        "theorem": (
            "For every centered complex A4 momentum q=p+i eta with "
            "||eta||<=0.031, F_r(q) is nonzero at the unique minimax root."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    r_star = brentq(
        stationarity_polynomial,
        ROOT_BRACKET[0],
        ROOT_BRACKET[1],
        xtol=5.0e-15,
        rtol=1.0e-15,
    )
    selected = relaxation_data(r_star)
    locality_proxy = relaxation_data(R_LOCALITY_PROXY)

    urt_radial_multiplier = abs(5.0 - 4.0 * math.pi / math.e)
    abs_h_factor = selected["optimal_Richardson_factor_for_abs_H"]

    exact_derivative_identity = {
        "spectral_ratio": (
            "K(r)=((5r-2)^2(4r^2-5))/(4(8r-9))"
        ),
        "log_derivative": (
            "K'(r)/K(r)=10/(5r-2)+8r/(4r^2-5)-8/(8r-9)"
        ),
        "combined_numerator": (
            "2(240r^3-392r^2-28r+185)"
        ),
        "consequence": (
            "Every strictly increasing function of K has the same unique "
            "minimizer r_star on the proved admissible branch."
        ),
    }

    strip = certified_strip_bound(
        str(ROOT_BRACKET[0]), str(ROOT_BRACKET[1]), str(TAU_CERTIFIED)
    )
    if not strip["zero_exclusion"]:
        raise RuntimeError("certified strip inequality did not close")

    out = {
        "certificate": "URT A4 contraction selector and certified locality",
        "date": "2026-09-04",
        "observational_targets_used": False,
        "input_status": {
            "exact_prior_input": (
                "The sharp global A4 spectral endpoints and unique minimax "
                "stationarity root proved on 2026-09-03."
            ),
            "formalized_URT_rule": (
                "Select the normalized microscopic member with maximal uniform "
                "worst-mode contraction of its positive quadratic relaxation."
            ),
            "status_warning": (
                "The mathematical consequence is exact. Calling this precise "
                "optimization rule the fundamental physical URT axiom is an "
                "explicit premise, not an empirical theorem."
            ),
        },
        "exact_selector_theorem": {
            "stationarity_polynomial": "240r^3-392r^2-28r+185=0",
            "isolating_interval": [str(ROOT_BRACKET[0]), str(ROOT_BRACKET[1])],
            "selected_r": r_star,
            "derivative_identity": exact_derivative_identity,
            "statement": (
                "Optimal scale-free Richardson relaxation of H_r^2, optimal "
                "Richardson relaxation of |H_r|, and every strictly monotone "
                "condition-number convergence criterion select the same unique r_star."
            ),
            "status": "E conditional on the explicitly formalized URT rule",
        },
        "selected_kernel": selected,
        "comparison_with_complex_strip_proxy": {
            "r_locality_proxy": R_LOCALITY_PROXY,
            "locality_proxy_kernel": locality_proxy,
            "H_squared_relaxation_factor_increase_percent": 100.0
            * (
                locality_proxy["optimal_Richardson_factor_for_H_squared"]
                / selected["optimal_Richardson_factor_for_H_squared"]
                - 1.0
            ),
            "abs_H_relaxation_factor_increase_percent": 100.0
            * (
                locality_proxy["optimal_Richardson_factor_for_abs_H"]
                / selected["optimal_Richardson_factor_for_abs_H"]
                - 1.0
            ),
            "conclusion": (
                "The searched strip maximizer is strictly worse under the URT "
                "uniform-contraction objective and is not selected by that rule."
            ),
        },
        "certified_complex_strip": strip,
        "frozen_URT_radial_multiplier_test": {
            "URT_radial_multiplier": urt_radial_multiplier,
            "minimum_abs_H_Richardson_factor": abs_h_factor,
            "difference": abs_h_factor - urt_radial_multiplier,
            "relative_difference_percent": 100.0
            * (abs_h_factor / urt_radial_multiplier - 1.0),
            "verdict": (
                "NO exact equality: the frozen URT radial multiplier lies below "
                "the globally minimal normalized kernel factor. The numerical "
                "near-match cannot be promoted to an identity."
            ),
        },
        "what_closes": [
            "r is unique if URT is explicitly defined by maximal uniform contraction",
            "r_star has a rigorously nonzero analytic strip and hence an exponential-locality bound",
            "r_locality_proxy is not a competing selector under that precise URT rule",
        ],
        "what_remains_open": [
            "derivation of the formalized URT rule from one microscopic physical action",
            "history Mobius parameter and finite wall extent/boundary data",
            "microscopic gauge-link bulk action",
            "determinant-line trivialization lambda",
            "parameter-free phenomenology and empirical tests",
        ],
        "phenomenology_gate": "CLOSED",
    }

    rendered = json.dumps(out, indent=2, sort_keys=True) + "\n"
    if args.output is None:
        print(rendered, end="")
    else:
        args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()