#!/usr/bin/env python3
"""Exact quasi-free merger and selection-boundary audit for Cathedral/URT.

Let rho0 be a gauge-invariant fermionic quasi-free Gibbs state generated by
dGamma(H0), and add a one-particle cost V through

    F(rho)=D(rho||rho0)+Tr[rho dGamma(V)].

The unique minimizer is exactly the quasi-free Gibbs state generated by
dGamma(H0+V), without requiring [H0,V]=0.  Its partition function and covariance
are det(1+exp[-(H0+V)]) and (1+exp[H0+V])^-1.

This is a constructive merger, but not a selector: every faithful one-particle
covariance Q is obtained by V=log((I-Q)Q^-1)-H0.  Moreover a generic
number-preserving many-body cost is not a second quantization dGamma(V).  For
four modes, the latter family plus a scalar has real dimension 17 inside the
70-dimensional number-preserving Hermitian algebra.

No observational target is used.
"""

from __future__ import annotations

import argparse
import json
import math
from math import comb
from pathlib import Path

import numpy as np
from scipy.linalg import expm


def annihilation_operators(mode_count: int) -> list[np.ndarray]:
    dimension = 1 << mode_count
    operators: list[np.ndarray] = []
    for mode in range(mode_count):
        operator = np.zeros((dimension, dimension), dtype=complex)
        for state in range(dimension):
            if (state >> mode) & 1:
                target = state ^ (1 << mode)
                parity = (state & ((1 << mode) - 1)).bit_count()
                operator[target, state] = -1.0 if parity % 2 else 1.0
        operators.append(operator)
    return operators


def second_quantize(one_particle: np.ndarray, annihilators: list[np.ndarray]) -> np.ndarray:
    dimension = annihilators[0].shape[0]
    result = np.zeros((dimension, dimension), dtype=complex)
    for i, annihilator_i in enumerate(annihilators):
        creator_i = annihilator_i.conj().T
        for j, annihilator_j in enumerate(annihilators):
            result += one_particle[i, j] * creator_i @ annihilator_j
    return result


def gibbs_density(hamiltonian: np.ndarray) -> tuple[np.ndarray, float]:
    boltzmann = expm(-hamiltonian)
    partition = float(np.trace(boltzmann).real)
    return boltzmann / partition, partition


def matrix_function_hermitian(matrix: np.ndarray, function) -> np.ndarray:
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)
    return eigenvectors @ np.diag(function(eigenvalues)) @ eigenvectors.conj().T


def one_particle_covariance(
    density: np.ndarray, annihilators: list[np.ndarray]
) -> np.ndarray:
    n = len(annihilators)
    covariance = np.zeros((n, n), dtype=complex)
    # Convention Q_ij=<c_j^dagger c_i>.
    for i in range(n):
        for j in range(n):
            covariance[i, j] = np.trace(
                density @ annihilators[j].conj().T @ annihilators[i]
            )
    return covariance


def hermitian_log_positive(matrix: np.ndarray) -> np.ndarray:
    return matrix_function_hermitian(matrix, np.log)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    rng = np.random.default_rng(20260904)
    n = 4
    annihilators = annihilation_operators(n)

    # A genuinely noncommuting general witness establishes that no commutativity
    # hypothesis is hidden in the merger identity.
    h0 = np.diag([0.35, 0.9, 1.55, 2.4]).astype(complex)
    raw = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    v = 0.18 * (raw + raw.conj().T)
    h_eff = h0 + v
    dgamma_h0 = second_quantize(h0, annihilators)
    dgamma_v = second_quantize(v, annihilators)
    dgamma_eff = second_quantize(h_eff, annihilators)
    rho0, z0 = gibbs_density(dgamma_h0)
    rho_eff_direct, z_eff = gibbs_density(dgamma_eff)

    # Variational Gibbs form obtained directly from log(rho0)-dGamma(V).
    log_rho0 = matrix_function_hermitian(rho0, np.log)
    variational_exponent = log_rho0 - dgamma_v
    variational_unnormalized = expm(variational_exponent)
    rho_eff_variational = variational_unnormalized / np.trace(
        variational_unnormalized
    )

    determinant_partition = float(
        np.linalg.det(np.eye(n) + expm(-h_eff)).real
    )
    q_fock = one_particle_covariance(rho_eff_direct, annihilators)
    q_formula = np.linalg.inv(np.eye(n) + expm(h_eff))

    commutator_norm = float(np.linalg.norm(h0 @ v - v @ h0, ord=2))
    merger_residual = float(
        np.linalg.norm(rho_eff_direct - rho_eff_variational, ord=2)
    )
    dgamma_linearity_residual = float(
        np.linalg.norm(dgamma_eff - dgamma_h0 - dgamma_v, ord=2)
    )
    partition_residual = abs(z_eff - determinant_partition)
    covariance_residual = float(np.linalg.norm(q_fock - q_formula, ord=2))

    # The minimum value is log Z0-log Z_eff.  Evaluate it directly.
    log_rho_eff = matrix_function_hermitian(rho_eff_direct, np.log)
    relative_entropy = float(
        np.trace(rho_eff_direct @ (log_rho_eff - log_rho0)).real
    )
    cost_expectation = float(np.trace(rho_eff_direct @ dgamma_v).real)
    functional_minimum_direct = relative_entropy + cost_expectation
    functional_minimum_formula = math.log(z0) - math.log(z_eff)

    # Surjectivity: choose an arbitrary faithful, nondiagonal covariance Q and
    # reconstruct the unique one-particle effective Hamiltonian and cost.
    raw_u = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    unitary, _ = np.linalg.qr(raw_u)
    q_target = unitary @ np.diag([0.08, 0.21, 0.43, 0.77]) @ unitary.conj().T
    h_target = hermitian_log_positive(
        (np.eye(n) - q_target) @ np.linalg.inv(q_target)
    )
    v_target = h_target - h0
    q_reconstructed = np.linalg.inv(np.eye(n) + expm(h0 + v_target))
    inverse_map_residual = float(
        np.linalg.norm(q_reconstructed - q_target, ord=2)
    )

    number_sector_dimensions = [comb(n, k) for k in range(n + 1)]
    number_preserving_hermitian_dimension = sum(
        dimension**2 for dimension in number_sector_dimensions
    )
    one_body_plus_scalar_dimension = n**2 + 1

    # Positivity does not select V: gamma |u><u| is a continuous admissible ray.
    vector = np.array([1.0, 1.0j, -1.0, 2.0j], dtype=complex)
    vector /= np.linalg.norm(vector)
    rank_one_projector = np.outer(vector, vector.conj())
    positive_family = []
    cathedral_h0 = 5.995797986741314 * np.eye(n)
    for gamma in (0.0, 0.25, 1.0, 4.0):
        v_gamma = gamma * rank_one_projector
        q_gamma = np.linalg.inv(np.eye(n) + expm(cathedral_h0 + v_gamma))
        positive_family.append(
            {
                "gamma": gamma,
                "minimum_eigenvalue_V": float(np.min(np.linalg.eigvalsh(v_gamma))),
                "covariance_trace": float(np.trace(q_gamma).real),
                "covariance_distance_from_gamma_0": float(
                    np.linalg.norm(
                        q_gamma
                        - np.linalg.inv(np.eye(n) + expm(cathedral_h0)),
                        ord=2,
                    )
                ),
            }
        )

    out = {
        "certificate": "URT exact quasi-free Gibbs merger and selection boundary",
        "date": "2026-09-04",
        "observational_targets_used": False,
        "theorem": {
            "prior": "rho0=exp[-dGamma(H0)]/Z0",
            "functional": "F_V(rho)=D(rho||rho0)+Tr[rho dGamma(V)]",
            "unique_minimizer": (
                "rho_V=exp[-dGamma(H0+V)]/det(I+exp[-(H0+V)])"
            ),
            "minimum": "min F_V=log Z0-log Z_V",
            "covariance": "Q_V=(I+exp(H0+V))^-1",
            "commutativity_required": False,
            "proof": (
                "Insert log rho0=-dGamma(H0)-log Z0 and use linearity of "
                "dGamma; the Gibbs variational identity then applies to H0+V."
            ),
            "status": "E",
        },
        "noncommuting_finite_witness": {
            "H0_V_commutator_norm": commutator_norm,
            "dGamma_linearity_residual": dgamma_linearity_residual,
            "density_merger_residual": merger_residual,
            "partition_determinant_residual": partition_residual,
            "covariance_formula_residual": covariance_residual,
            "functional_minimum_direct": functional_minimum_direct,
            "functional_minimum_formula": functional_minimum_formula,
            "functional_minimum_residual": abs(
                functional_minimum_direct - functional_minimum_formula
            ),
        },
        "inverse_selection_theorem": {
            "domain": "every faithful covariance Q with 0<Q<I",
            "inverse": "V_Q=log((I-Q)Q^-1)-H0",
            "reconstruction_residual": inverse_map_residual,
            "consequence": (
                "The variational principle is a bijective response map once V is "
                "supplied; it imposes no target-blind choice among faithful Q."
            ),
            "status": "E",
        },
        "second_quantization_scope": {
            "mode_count": n,
            "Fock_dimension": 1 << n,
            "number_sector_dimensions": number_sector_dimensions,
            "number_preserving_Hermitian_real_dimension": (
                number_preserving_hermitian_dimension
            ),
            "dGamma_one_body_plus_global_scalar_real_dimension": (
                one_body_plus_scalar_dimension
            ),
            "codimension": (
                number_preserving_hermitian_dimension
                - one_body_plus_scalar_dimension
            ),
            "identity": "sum_k binomial(4,k)^2=binomial(8,4)=70",
            "consequence": (
                "A generic number-preserving 16x16 cost, including a generic "
                "positive Gram, has no one-particle V whose second quantization it is."
            ),
            "status": "E",
        },
        "positive_cost_nonuniqueness": {
            "family": "V_gamma=gamma |u><u|, gamma>=0",
            "samples": positive_family,
            "consequence": (
                "Even restricting the supplied one-particle history cost to positive "
                "Grams leaves continuous inequivalent Gibbs states."
            ),
            "status": "E",
        },
        "reflection_positivity_and_locality_boundary": {
            "finite_result": (
                "H0+V defines a valid finite unitary inner dynamics and its Gibbs "
                "state once V and a time normalization are supplied."
            ),
            "not_implied": (
                "a lattice-local kernel, a reflection operation, Osterwalder-Schrader "
                "positivity, a Lorentzian continuation, chirality or anomaly measure"
            ),
            "reason": (
                "The response functional is defined on a static density matrix and "
                "is covariant under arbitrary one-particle basis changes; those extra "
                "spacetime structures are absent from its premises."
            ),
            "status": "U pending an independently specified local history/Dirac block",
        },
        "verdict": {
            "canonical_merger_given_H0_and_V": "E",
            "history_cost_V_selected_by_relative_information": "F",
            "generic_many_body_Gram_is_one_body_Dirac_cost": "F",
            "reflection_positive_local_dynamics_derived": "F",
            "advance": (
                "The relative-information principle exactly closes the algebra of a "
                "supplied quasi-free cost, including noncommuting matrices.  It is a "
                "response theorem, not a generator-selection theorem: V is in exact "
                "bijection with the desired faithful covariance and generic stored "
                "many-body costs lie outside dGamma's 17-dimensional image."
            ),
            "phenomenology_gate": "CLOSED",
        },
    }

    rendered = json.dumps(out, indent=2, sort_keys=True) + "\n"
    if args.output is None:
        print(rendered, end="")
    else:
        args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()