#!/usr/bin/env python3
"""Exact KMS-state versus Dirac-geometry selection audit for Cathedral/URT.

The passive 16-state prior is exactly the fermionic Fock Gibbs state of four
equal positive one-particle energies.  This script asks the stronger question:
does that state select a nontrivial Dirac geometry?

For an ordinary finite CAR Gibbs state generated by dGamma(A), restriction of
the density matrix to the one-particle sector relative to the vacuum is
exp(-beta A).  The Cathedral prior makes this matrix Delta I_4.  Consequently
beta A=(-log Delta)I_4, and at beta=eta_Delta the positive generator is I_4.
It commutes with every represented algebra and produces no Connes one-forms.

Allowing a signed Dirac operator D with |D|=I_4 restores possible nonzero
commutators, but the KMS state and the even entropy spectral action are then
blind to the sign involution.  An explicit continuous family exhibits this
ambiguity.  Full A5 covariance on its irreducible V4 carrier collapses the
family to D=+/-I by Schur's lemma, which is again geometrically trivial.

The hidden 3+5 cost block has a related U(8)/(U(4)xU(4)) eigenspace ambiguity.
No observational target is used.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np


ETA_DELTA = 5.995797986741314
DELTA = 0.002489189840420375


def entropy_cutoff(x: float) -> float:
    return math.log1p(math.exp(-x)) + x / (1.0 + math.exp(x))


def signed_dirac(theta: float) -> np.ndarray:
    """A self-adjoint involution with a rotating +/- eigenspace split."""
    c = math.cos(2.0 * theta)
    s = math.sin(2.0 * theta)
    return np.array(
        [
            [c, s, 0.0, 0.0],
            [s, -c, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, -1.0],
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    delta_from_eta = math.exp(-ETA_DELTA)

    # The one-particle/vacuum density-block ratio of the passive Fock prior.
    vacuum_weight = 1.0 / (1.0 + DELTA) ** 4
    one_particle_block = (
        DELTA / (1.0 + DELTA) ** 4 * np.eye(4, dtype=float)
    )
    relative_one_particle_block = one_particle_block / vacuum_weight
    reconstructed_beta_A = -np.log(DELTA) * np.eye(4, dtype=float)
    reconstructed_A = reconstructed_beta_A / ETA_DELTA

    # A represented algebra element can be completely arbitrary here: I4
    # commutes with it.  A nonnormal witness makes this more than a diagonal
    # coincidence.
    algebra_witness = np.array(
        [
            [1.0, 2.0, 0.0, -1.0],
            [0.0, -3.0, 4.0, 0.0],
            [2.0, 0.0, 5.0, 1.0],
            [0.0, 1.0, -2.0, 7.0],
        ]
    )
    positive_commutator = reconstructed_A @ algebra_witness - algebra_witness @ reconstructed_A

    projector = np.diag([1.0, 0.0, 0.0, 0.0])
    theta_samples = [0.0, math.pi / 16.0, math.pi / 8.0, 3.0 * math.pi / 16.0]
    signed_family = []
    max_involution_residual = 0.0
    max_abs_residual = 0.0
    max_entropy_residual = 0.0
    for theta in theta_samples:
        d_theta = signed_dirac(theta)
        involution_residual = float(np.linalg.norm(d_theta @ d_theta - np.eye(4), ord=2))
        abs_eigenvalues, abs_eigenvectors = np.linalg.eigh(d_theta @ d_theta)
        abs_d = (
            abs_eigenvectors
            @ np.diag(np.sqrt(np.maximum(abs_eigenvalues, 0.0)))
            @ abs_eigenvectors.T
        )
        abs_residual = float(np.linalg.norm(abs_d - np.eye(4), ord=2))
        commutator = d_theta @ projector - projector @ d_theta
        commutator_norm = float(np.linalg.norm(commutator, ord=2))
        expected_commutator_norm = abs(math.sin(2.0 * theta))
        spectral_entropy = 4.0 * entropy_cutoff(ETA_DELTA)
        expected_entropy = 4.0 * entropy_cutoff(ETA_DELTA)
        entropy_residual = abs(spectral_entropy - expected_entropy)
        max_involution_residual = max(max_involution_residual, involution_residual)
        max_abs_residual = max(max_abs_residual, abs_residual)
        max_entropy_residual = max(max_entropy_residual, entropy_residual)
        signed_family.append(
            {
                "theta": theta,
                "operator_commutator_norm_with_P": commutator_norm,
                "expected_abs_sin_2theta": expected_commutator_norm,
                "commutator_formula_residual": abs(
                    commutator_norm - expected_commutator_norm
                ),
                "D_squared_minus_I_norm": involution_residual,
                "abs_D_minus_I_norm": abs_residual,
                "entropy": spectral_entropy,
            }
        )

    # Hidden cost K=3I+2Q: rotating a rank-four projector preserves the 3^4+5^4
    # spectrum but changes its eigenspaces.  A two-coordinate rotation supplies
    # a concrete continuous witness.
    q0 = np.diag([0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0])
    hidden_samples = []
    max_hidden_spectrum_residual = 0.0
    for theta in theta_samples:
        rotation = np.eye(8)
        rotation[0, 0] = math.cos(theta)
        rotation[0, 4] = -math.sin(theta)
        rotation[4, 0] = math.sin(theta)
        rotation[4, 4] = math.cos(theta)
        q_theta = rotation @ q0 @ rotation.T
        k_theta = 3.0 * np.eye(8) + 2.0 * q_theta
        spectrum = np.linalg.eigvalsh(k_theta)
        expected = np.array([3.0] * 4 + [5.0] * 4)
        spectrum_residual = float(np.max(np.abs(spectrum - expected)))
        max_hidden_spectrum_residual = max(
            max_hidden_spectrum_residual, spectrum_residual
        )
        hidden_samples.append(
            {
                "theta": theta,
                "projector_distance_from_theta_0": float(
                    np.linalg.norm(q_theta - q0, ord="fro")
                ),
                "spectrum": spectrum.tolist(),
                "spectrum_residual": spectrum_residual,
            }
        )

    out = {
        "certificate": "URT KMS state versus Dirac geometry selection no-go",
        "date": "2026-09-04",
        "observational_targets_used": False,
        "passive_state_reconstruction": {
            "state": "rho0=Delta^N/(1+Delta)^4 on Fock(C^4)",
            "Delta": DELTA,
            "eta_Delta": ETA_DELTA,
            "Delta_minus_exp_minus_eta_residual": abs(DELTA - delta_from_eta),
            "one_particle_to_vacuum_block": relative_one_particle_block.tolist(),
            "theorem": (
                "For rho proportional exp[-beta dGamma(A)], the one-particle/"
                "vacuum block ratio is exp(-beta A).  Here it is Delta I4, so "
                "beta A=(-log Delta)I4."
            ),
            "reconstructed_beta_A": reconstructed_beta_A.tolist(),
            "reconstructed_A_at_beta_eta_Delta": reconstructed_A.tolist(),
            "A_minus_I_norm": float(
                np.linalg.norm(reconstructed_A - np.eye(4), ord=2)
            ),
            "commutator_with_arbitrary_algebra_witness_norm": float(
                np.linalg.norm(positive_commutator, ord=2)
            ),
            "Connes_one_forms": "Omega^1_A={sum a[D,b]}=0 for D=A=I4",
            "status": "E conditional on the ordinary positive CAR Gibbs identification",
        },
        "signed_Dirac_ambiguity": {
            "premise": (
                "If the state Hamiltonian is |D|, the passive state fixes only "
                "|D|=I4; every self-adjoint involution D remains invisible to it."
            ),
            "family": (
                "D(theta)=[[cos2t,sin2t], [sin2t,-cos2t]] direct-sum [1] direct-sum [-1]"
            ),
            "samples": signed_family,
            "max_D_squared_minus_I_norm": max_involution_residual,
            "max_abs_D_minus_I_norm": max_abs_residual,
            "max_entropy_identity_residual": max_entropy_residual,
            "continuous_moduli_example": "fixed-signature orbit U(4)/(U(2)xU(2))",
            "real_dimension_of_example_moduli": 8,
            "geometry_changes": (
                "For P=diag(1,0,0,0), ||[D(theta),P]||=|sin(2 theta)| "
                "although |D(theta)|, the KMS state and Tr h(eta D(theta)) are fixed."
            ),
            "status": "E",
        },
        "A5_covariance_dichotomy": {
            "carrier": "irreducible complex V4 of A5",
            "Schur_commutant": "End_A5(V4)=C I4",
            "consequence": (
                "An A5-equivariant self-adjoint involution is D=+I4 or -I4. "
                "Both commute with every algebra element and have zero one-forms."
            ),
            "dichotomy": (
                "Keep full A5 covariance and obtain a trivial Dirac geometry, or "
                "relax it and introduce an entropy-invisible continuous sign choice."
            ),
            "status": "E",
        },
        "hidden_3_5_eigenspace_ambiguity": {
            "cost_family": "K(Q)=3 I8+2Q for any rank-four orthogonal projector Q",
            "spectrum_for_every_Q": {"3": 4, "5": 4},
            "moduli": "U(8)/(U(4)xU(4))=Gr_C(4,8)",
            "real_dimension": 32,
            "samples": hidden_samples,
            "max_spectrum_residual": max_hidden_spectrum_residual,
            "consequence": (
                "The stored spectrum and entropy do not select the hidden eigenspaces, "
                "their tensor-factor identification or their coupling to geometry."
            ),
            "status": "E",
        },
        "verdict": {
            "passive_prior_is_finite_KMS_state": "E",
            "positive_generator_is_nontrivial_geometry": "F",
            "signed_Dirac_selected_by_state_or_even_entropy": "F",
            "A5_equivariant_nontrivial_Dirac_from_prior": "F",
            "unique_hidden_eigenspace_from_3_5_spectrum": "F",
            "advance": (
                "The exact finite KMS factorization does not supply the missing "
                "Dirac operator.  In the positive reading it uniquely returns a "
                "scalar generator with zero differential calculus; in the signed "
                "reading it leaves a continuous entropy-invisible geometry choice."
            ),
            "phenomenology_gate": "CLOSED",
        },
    }

    rendered = json.dumps(out, indent=2, sort_keys=True) + "\n"
    if args.output is None:
        print(rendered, end="")
    else:
        args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()