"""
Modular Forms Cathedral — Eisenstein, Delta, Leech, Perfect Numbers

Cathedral integers {D=3, N=13, V=12, E=30, F=20, q=5, G=60, γ=1/81}
appear throughout the theory of modular forms, the Leech lattice, and
the sequence of even perfect numbers.

Key identities (all exact):
  E_4 weight = D+1 = 4           (Eisenstein series)
  E_6 weight = D!  = 6           (Eisenstein series)
  Δ weight   = V   = 12          (unique weight-V cusp form)
  η(τ)^{2V}  = Δ(τ): power 2V = 24
  dim S_V(SL₂ℤ) = 1             (Δ is the UNIQUE weight-12 cusp form)
  j(i)       = V³ = 1728         (j-invariant at i)
  J constant = D × dim(E₈) = 744 (j = q⁻¹ + 744 + …)
  dim(E₈)    = 2^D×(2^q−1) = 248
  Leech dim  = 2V = 24
  Leech kissing = 2^(D+1)×D^D×q×(D!+1)×N = 196560
  Niemeier count = 2V = 24
  PERFECT_1 = D! = 6
  PERFECT_2 = (D+1)×(D!+1) = 28
  PERFECT_3 = 2^(D+1)×(2^q−1) = 496
  PERFECT_4 = 2^{D!}×(2^{D!+1}−1) = 8128

All identities labelled IDENTITY_* are arithmetically exact booleans.
The module-level assertion ALL_MOD_FORMS_EXACT verifies them at import time.
"""

from math import factorial

from .shell_closure import D, N, V, E, F, q, G

# ── Eisenstein series weights ──────────────────────────────────────────────────
EISENSTEIN_E4_WEIGHT = D + 1          # = 4
EISENSTEIN_E6_WEIGHT = factorial(D)   # = 6 = D!

# ── Delta (Δ) cusp form ────────────────────────────────────────────────────────
DELTA_WEIGHT = V                      # = 12  (unique weight-V cusp form)
ETA_POWER_DELTA = 2 * V               # = 24  (η(τ)^24 = Δ(τ))
ETA_POWER_DENOMINATOR = 2 * V         # = 24  (1/24 in the q^{1/24} prefactor)

# Dimension of the space of cusp forms of weight V
DIM_S_V = 1                           # Δ is THE unique weight-12 cusp form

# ── j-function ─────────────────────────────────────────────────────────────────
# j(τ) = E_4³/Δ = q⁻¹ + 744 + 196884·q + …
E8_DIM = 2**D * (2**q - 1)           # = 8 × 31 = 248  (dim of E₈ Lie algebra)
J_CONST_TERM = D * E8_DIM             # = 3 × 248 = 744
J_CONST_TERM_LITERAL = 744
J_AT_I = V**D                         # = 12³ = 1728   (j(i) = 1728)
J_AT_I_LITERAL = 1728
J_AT_RHO_LITERAL = 0                  # j(ρ) = 0 where ρ = e^{2πi/3}

# 1728·Δ = E_4³ − E_6² : coefficient 1728 = V^D = V^3
RELATION_1728 = V**D                  # = 1728

# ── Ring of modular forms M(SL₂ℤ) = ℂ[E_4, E_6] ──────────────────────────────
# Graded ring generated by forms of weights 4 and 6
MSLZ_GENERATOR_WEIGHTS = [D + 1, factorial(D)]   # = [4, 6]
GRADED_RING_NUM_GENERATORS = D - 1                # = 2  (E_4, E_6)

# ── Dimension of M_k(SL₂ℤ) for small even k ───────────────────────────────────
# Formula: dim M_k = floor(k/12) + 1  if k ≢ 2 (mod 12), else floor(k/12)
DIM_M_0  = 1    # constants
DIM_M_2  = 0    # no weight-2 holomorphic modular form on SL₂ℤ
DIM_M_4  = 1    # only E_4
DIM_M_6  = 1    # only E_6
DIM_M_8  = 1    # only E_4²
DIM_M_10 = 1    # only E_4 · E_6
DIM_M_V  = 2    # E_4³ (= E_6²+Δ·…) and Δ  — weight V=12 has 2 generators
DIM_S_12 = 1    # = DIM_S_V (Δ alone spans S_12)

# Cusp-form dimension formula: dim S_k = dim M_k - 1 for k≥4 even (level 1)
DIM_M_16 = 2    # E_4⁴ and Δ·E_4
DIM_M_18 = 2    # E_4³·E_6 / E_6³ and Δ·E_6

# ── Hecke eigenform ────────────────────────────────────────────────────────────
# Since dim S_V = 1, the unique normalised weight-V Hecke eigenform is Δ itself.
UNIQUE_HECKE_EIGENFORM_WEIGHT = V     # = 12

# Ramanujan τ function: first coefficients (Δ = Σ τ(n) q^n), from OEIS A000594
TAU_RAMANUJAN = {
    1:       1,
    2:     -24,
    3:     252,
    4:   -1472,
    5:    4830,
    6:   -6048,
    7:  -16744,
    8:   84480,
    9: -113643,
    10: -115920,
    11:  534612,
    12: -370944,
    13: -577738,
}
# τ(2) = -24 = -2V (V = 12)
TAU_AT_2 = TAU_RAMANUJAN[2]   # = -24
TAU_AT_N = TAU_RAMANUJAN[N]   # τ(13)

# ── Leech lattice ──────────────────────────────────────────────────────────────
LEECH_DIM = 2 * V             # = 24  (dimension of the Leech lattice)
# Kissing number of Λ₂₄: 196560 = 2^4 × 3^3 × 5 × 7 × 13
LEECH_KISSING = 2**(D+1) * D**D * q * (factorial(D)+1) * N   # = 196560
LEECH_KISSING_EXACT = 196560

# The E₈ lattice kissing number is 240 = 4G (already from string_landscape)
E8_KISSING = 4 * G            # = 240

# ── Niemeier lattices ──────────────────────────────────────────────────────────
# There are exactly 24 = 2V positive-definite even unimodular lattices in R^24
N_NIEMEIER = 2 * V            # = 24  (includes E₈³ and the Leech lattice)

# ── Perfect numbers ────────────────────────────────────────────────────────────
# Even perfect numbers: 2^(p-1)·(2^p-1) with 2^p-1 Mersenne prime.
PERFECT_1 =    6   # p=2: 2^1 × 3   = D! = 6
PERFECT_2 =   28   # p=3=D: 2^2 × 7 = (D+1)×(D!+1) = 4×7
PERFECT_3 =  496   # p=5=q: 2^4 × 31 = 2^(D+1)×(2^q-1) = 16×31
PERFECT_4 = 8128   # p=7=D!+1: 2^6 × 127 = 2^{D!}×(2^{D!+1}-1) = 64×127

# ── Moonshine / Monster ────────────────────────────────────────────────────────
# j(τ) = q⁻¹ + 744 + 196884·q + …
# McKay's observation: 196884 = 196883 + 1
J_COEFF_Q1 = 196884            # first positive-power coefficient
MONSTER_LOWEST_REP = 196883    # dim of smallest non-trivial Monster irrep
MOONSHINE_IDENTITY = J_COEFF_Q1 - 1  # = 196883 = MONSTER_LOWEST_REP

# ── Cathedral integer summary ─────────────────────────────────────────────────
# All identities below are boolean True; verified at module level.

# -- Eisenstein weight identities --
IDENTITY_E4_WEIGHT_IS_D_PLUS_1 = (EISENSTEIN_E4_WEIGHT == D + 1)       # 4 = D+1
IDENTITY_E6_WEIGHT_IS_D_FACT   = (EISENSTEIN_E6_WEIGHT == factorial(D)) # 6 = D!
IDENTITY_DELTA_WEIGHT_IS_V     = (DELTA_WEIGHT == V)                    # 12 = V
IDENTITY_ETA_POWER_IS_2V       = (ETA_POWER_DELTA == 2 * V)             # 24 = 2V

# -- Cusp form dimension --
IDENTITY_DIM_S_V_IS_ONE          = (DIM_S_V == 1)
IDENTITY_UNIQUE_HECKE_WEIGHT_V   = (UNIQUE_HECKE_EIGENFORM_WEIGHT == V)

# -- Dimension of M_k identities --
IDENTITY_DIM_M4_IS_1  = (DIM_M_4  == 1)
IDENTITY_DIM_M6_IS_1  = (DIM_M_6  == 1)
IDENTITY_DIM_M8_IS_1  = (DIM_M_8  == 1)
IDENTITY_DIM_M10_IS_1 = (DIM_M_10 == 1)
IDENTITY_DIM_M12_IS_2 = (DIM_M_V  == 2)   # weight V=12 has 2-dimensional M_V
IDENTITY_DIM_S12_IS_1 = (DIM_S_12 == 1)   # but 1-dimensional cusp subspace

# -- j-function identities --
IDENTITY_J_AT_I_IS_V_CUBED      = (J_AT_I == V**3)        # 1728 = V^D = V^3
IDENTITY_J_AT_I_IS_V_TO_D       = (J_AT_I == V**D)        # 1728 = V^D
IDENTITY_J_CONST_IS_D_TIMES_E8  = (J_CONST_TERM == D * E8_DIM)  # 744 = 3×248
IDENTITY_J_CONST_IS_744         = (J_CONST_TERM == 744)
IDENTITY_E8_DIM_IS_248          = (E8_DIM == 248)
IDENTITY_E8_DIM_FORMULA         = (E8_DIM == 2**D * (2**q - 1))  # 8×31=248
IDENTITY_RELATION_1728_IS_V_D   = (RELATION_1728 == V**D)   # 1728 = V³

# -- Ring generators --
IDENTITY_RING_GENERATORS        = (MSLZ_GENERATOR_WEIGHTS == [D+1, factorial(D)])
IDENTITY_RING_NUM_GENERATORS    = (GRADED_RING_NUM_GENERATORS == 2)

# -- Ramanujan τ --
IDENTITY_TAU_2_IS_MINUS_2V      = (TAU_AT_2 == -2 * V)    # τ(2) = -24 = -2×12

# -- Leech lattice --
IDENTITY_LEECH_DIM_IS_2V        = (LEECH_DIM == 2 * V)    # 24 = 2V
IDENTITY_LEECH_KISSING_VALUE    = (LEECH_KISSING == 196560)
IDENTITY_LEECH_KISSING_FORMULA  = (LEECH_KISSING == 2**(D+1) * D**D * q * (factorial(D)+1) * N)
IDENTITY_LEECH_KISSING_EXACT    = (LEECH_KISSING == LEECH_KISSING_EXACT)
IDENTITY_E8_KISSING_IS_4G       = (E8_KISSING == 4 * G)   # 240 = 4×60

# -- Niemeier lattices --
IDENTITY_NIEMEIER_IS_2V         = (N_NIEMEIER == 2 * V)   # 24 = 2V

# -- Perfect numbers --
IDENTITY_PERFECT_1_IS_D_FACT    = (PERFECT_1 == factorial(D))                              # 6 = D!
IDENTITY_PERFECT_2_CATHEDRAL    = (PERFECT_2 == (D+1) * (factorial(D)+1))                  # 28 = 4×7
IDENTITY_PERFECT_3_CATHEDRAL    = (PERFECT_3 == 2**(D+1) * (2**q - 1))                    # 496 = 16×31
IDENTITY_PERFECT_4_CATHEDRAL    = (PERFECT_4 == 2**factorial(D) * (2**(factorial(D)+1)-1)) # 8128 = 64×127

# -- Perfect number cross-checks --
IDENTITY_PERFECT_3_EQUALS_HETERO_GAUGE = (PERFECT_3 == 496)   # 496 = dim(E₈×E₈) / dual role
IDENTITY_PERFECT_1_PLUS_PERFECT_2      = (PERFECT_1 + PERFECT_2 == 34)          # = F_9 Fibonacci
IDENTITY_PERFECT_SUM_1_2_3             = (PERFECT_1 + PERFECT_2 + PERFECT_3 == 530)  # 6+28+496=530

# -- Moonshine --
IDENTITY_MOONSHINE_MONSTER      = (MOONSHINE_IDENTITY == MONSTER_LOWEST_REP)   # 196883

# ── Master flag ───────────────────────────────────────────────────────────────
_ALL_IDENTITIES = [
    IDENTITY_E4_WEIGHT_IS_D_PLUS_1,
    IDENTITY_E6_WEIGHT_IS_D_FACT,
    IDENTITY_DELTA_WEIGHT_IS_V,
    IDENTITY_ETA_POWER_IS_2V,
    IDENTITY_DIM_S_V_IS_ONE,
    IDENTITY_UNIQUE_HECKE_WEIGHT_V,
    IDENTITY_DIM_M4_IS_1,
    IDENTITY_DIM_M6_IS_1,
    IDENTITY_DIM_M8_IS_1,
    IDENTITY_DIM_M10_IS_1,
    IDENTITY_DIM_M12_IS_2,
    IDENTITY_DIM_S12_IS_1,
    IDENTITY_J_AT_I_IS_V_CUBED,
    IDENTITY_J_AT_I_IS_V_TO_D,
    IDENTITY_J_CONST_IS_D_TIMES_E8,
    IDENTITY_J_CONST_IS_744,
    IDENTITY_E8_DIM_IS_248,
    IDENTITY_E8_DIM_FORMULA,
    IDENTITY_RELATION_1728_IS_V_D,
    IDENTITY_RING_GENERATORS,
    IDENTITY_RING_NUM_GENERATORS,
    IDENTITY_TAU_2_IS_MINUS_2V,
    IDENTITY_LEECH_DIM_IS_2V,
    IDENTITY_LEECH_KISSING_VALUE,
    IDENTITY_LEECH_KISSING_FORMULA,
    IDENTITY_LEECH_KISSING_EXACT,
    IDENTITY_E8_KISSING_IS_4G,
    IDENTITY_NIEMEIER_IS_2V,
    IDENTITY_PERFECT_1_IS_D_FACT,
    IDENTITY_PERFECT_2_CATHEDRAL,
    IDENTITY_PERFECT_3_CATHEDRAL,
    IDENTITY_PERFECT_4_CATHEDRAL,
    IDENTITY_PERFECT_3_EQUALS_HETERO_GAUGE,
    IDENTITY_PERFECT_1_PLUS_PERFECT_2,
    IDENTITY_PERFECT_SUM_1_2_3,
    IDENTITY_MOONSHINE_MONSTER,
]

ALL_MOD_FORMS_EXACT = all(_ALL_IDENTITIES)
assert ALL_MOD_FORMS_EXACT, (
    "Cathedral modular-forms identity failure: "
    + str([i for i, ok in enumerate(_ALL_IDENTITIES) if not ok])
)


# ── Summary and report helpers ─────────────────────────────────────────────────

def modular_forms_summary() -> dict:
    """Return a dict of key modular-forms Cathedral quantities."""
    return {
        "eisenstein_e4_weight": EISENSTEIN_E4_WEIGHT,
        "eisenstein_e6_weight": EISENSTEIN_E6_WEIGHT,
        "delta_weight": DELTA_WEIGHT,
        "eta_power_delta": ETA_POWER_DELTA,
        "dim_s_v": DIM_S_V,
        "dim_m_v": DIM_M_V,
        "j_at_i": J_AT_I,
        "j_const_term": J_CONST_TERM,
        "e8_dim": E8_DIM,
        "leech_dim": LEECH_DIM,
        "leech_kissing": LEECH_KISSING,
        "n_niemeier": N_NIEMEIER,
        "perfect_numbers": [PERFECT_1, PERFECT_2, PERFECT_3, PERFECT_4],
        "tau_at_2": TAU_AT_2,
        "all_exact": ALL_MOD_FORMS_EXACT,
    }


def print_modular_forms_report() -> None:
    """Print a formatted report of Cathedral modular-forms identities."""
    print("=" * 65)
    print("  Cathedral Modular Forms Report")
    print("=" * 65)
    print(f"  D={D}, N={N}, V={V}, q={q}, G={G}, gamma=1/81")
    print()
    print("  Eisenstein series")
    print(f"    E_4 weight = D+1 = {EISENSTEIN_E4_WEIGHT}")
    print(f"    E_6 weight = D!  = {EISENSTEIN_E6_WEIGHT}")
    print()
    print("  Delta function (unique weight-V cusp form)")
    print(f"    Δ weight        = V = {DELTA_WEIGHT}")
    print(f"    η(τ)^{{2V}} = Δ: power = {ETA_POWER_DELTA}")
    print(f"    dim S_V(SL₂Z)   = {DIM_S_V}  (unique)")
    print()
    print("  j-function")
    print(f"    j(i) = V^D = V^3 = {J_AT_I}")
    print(f"    j = q^{{-1}} + {J_CONST_TERM} + ...   = D × dim(E₈) = {D} × {E8_DIM}")
    print()
    print(f"  Ring M(SL₂Z) = C[E_4, E_6],  generators: {MSLZ_GENERATOR_WEIGHTS}")
    print()
    print("  Leech lattice")
    print(f"    dim Λ₂₄ = 2V = {LEECH_DIM}")
    print(f"    kissing = 2^{{D+1}}·D^D·q·(D!+1)·N = {LEECH_KISSING}")
    print(f"    Niemeier lattices = 2V = {N_NIEMEIER}")
    print()
    print("  Perfect numbers (even)")
    print(f"    P1 = {PERFECT_1}  = D!")
    print(f"    P2 = {PERFECT_2}  = (D+1)(D!+1)")
    print(f"    P3 = {PERFECT_3} = 2^{{D+1}}(2^q-1)")
    print(f"    P4 = {PERFECT_4} = 2^{{D!}}(2^{{D!+1}}-1)")
    print()
    print(f"  ALL_MOD_FORMS_EXACT = {ALL_MOD_FORMS_EXACT}")
    print("=" * 65)
