#!/usr/bin/env python3
"""See Newton_Cathedral_v117_Final_Mathematical_Closure.md for the full derivation.
This checkpoint was generated by an explicit NumPy/NetworkX enumeration of the
12 vertices, 30 oriented edges, 20 faces and all 60 A5 rotations.
The accompanying JSON records the numerical certificates.
"""
import json
from pathlib import Path
p=Path(__file__).with_name('Cathedral_v117_Final_Mathematical_Closure_results.json')
print(p.read_text())